# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aux1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditorWindow(object):
    def setupUi(self, EditorWindow):
        EditorWindow.setObjectName("EditorWindow")
        EditorWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(EditorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectedImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.selectedImage.setGeometry(QtCore.QRect(10, 30, 341, 541))
        self.selectedImage.setObjectName("selectedImage")
        self.colorsFound = QtWidgets.QFrame(self.centralwidget)
        self.colorsFound.setGeometry(QtCore.QRect(439, 29, 341, 541))
        self.colorsFound.setObjectName("colorsFound")
        self.gridLayout = QtWidgets.QGridLayout(self.colorsFound)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.colorsFound)
        self.frame.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.colorsFound)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        EditorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditorWindow)
        QtCore.QMetaObject.connectSlotsByName(EditorWindow)

    def retranslateUi(self, EditorWindow):
        _translate = QtCore.QCoreApplication.translate
        EditorWindow.setWindowTitle(_translate("EditorWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditorWindow = QtWidgets.QMainWindow()
    ui = Ui_EditorWindow()
    ui.setupUi(EditorWindow)
    EditorWindow.show()
    sys.exit(app.exec_())
