# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetColorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial


class Ui_Dialog(object):
    this_dialog = None
    manipulated_frame = None
    r_int = 0
    g_int = 0
    b_int = 0
    pixel_old_color = (0, 0, 0, 0)
    color_tuple = (0, 0, 0, 0)
    editor = None

    def update_pixel_color(self):
        self.this_dialog.close()
        self.editor.change_pixel_color(self.manipulated_frame, self.pixel_old_color, self.color_tuple)

    def color_value_changed(self, color_type, value):
        if color_type == 'R':
            self.r_int = value
        elif color_type == 'G':
            self.g_int = value
        else:
            self.b_int = value

        self.color_tuple = (self.r_int, self.g_int, self.b_int)
        stylesheet = 'background-color: rgb' + str(self.color_tuple)

        self.color_view.setStyleSheet(stylesheet)

    def setup_ui(self, Editor, Dialog, frame_to_manipulate):
        self.manipulated_frame = frame_to_manipulate
        self.this_dialog = Dialog
        self.editor = Editor
        self.pixel_old_color = frame_to_manipulate.color_code
        self.color_tuple = frame_to_manipulate.color_code

        self.r_int = frame_to_manipulate.color_code[0]
        self.g_int = frame_to_manipulate.color_code[1]
        self.b_int = frame_to_manipulate.color_code[2]

        Dialog.setObjectName("Dialog")
        Dialog.resize(240, 320)
        self.color_view = QtWidgets.QFrame(Dialog)
        self.color_view.setGeometry(QtCore.QRect(40, 99, 161, 121))
        self.color_view.setStyleSheet("border: 1px solid #000000")
        self.color_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.color_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.color_view.setObjectName("color_view")
        self.color_view.setStyleSheet('background-color: rgb' + str(self.color_tuple))
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(80, 250, 75, 23))
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(80, 280, 75, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.R_value = QtWidgets.QSpinBox(Dialog)
        self.R_value.setGeometry(QtCore.QRect(20, 60, 61, 22))
        self.R_value.setMaximum(255)
        self.R_value.setObjectName("R_value")
        self.R_value.setValue(self.r_int)
        self.G_value = QtWidgets.QSpinBox(Dialog)
        self.G_value.setGeometry(QtCore.QRect(90, 60, 61, 22))
        self.G_value.setMaximum(255)
        self.G_value.setObjectName("G_value")
        self.G_value.setValue(self.g_int)
        self.B_value = QtWidgets.QSpinBox(Dialog)
        self.B_value.setGeometry(QtCore.QRect(160, 60, 61, 22))
        self.B_value.setMaximum(255)
        self.B_value.setObjectName("B_value")
        self.B_value.setValue(self.b_int)

        self.R_value.valueChanged.connect(partial(self.color_value_changed, 'R'))
        self.G_value.valueChanged.connect(partial(self.color_value_changed, 'G'))
        self.B_value.valueChanged.connect(partial(self.color_value_changed, 'B'))
        self.confirm_button.clicked.connect(self.update_pixel_color)

        self.retranslate_ui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confirm_button.setText(_translate("Dialog", "Confirmar"))
        self.cancel_button.setText(_translate("Dialog", "Cancelar"))
        self.label.setText(_translate("Dialog", "Nova cor do pixel:"))

